---
- name: Configure EKS Cluster
  hosts: localhost
  gather_facts: false
  become: yes

  pre_tasks:
    - name: set aws environment variables
      set_fact:
        AWS_REGION: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
        AWS_KEY_ID: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  roles:
    - create-cluster