---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: fodmap-react
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fodmap-react
  template:
    metadata:
      labels:
        app: fodmap-react
    spec:
      containers:
        - name: fodmap-react
          image: floresarantza/fodmap-react-app:latest
          ports:
            - containerPort: 80