----
apiVersion: v1
kind: Deployment
metadata:
   name: fodmap-deployment
   namespace: fodmap-namespace
   labels:
    app: fodmap-app
spec:
  containers:
    - name: fodmap-app
      image: floresarantza/fodmap-react-app:${CIRCLE_WORKFLOW_ID:0:4}
      ports:
        - name: http
          containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: fodmap-service
  namespace: fodmap-namespace
  labels:
    app: fodmap-app
spec:
  type: LoadBalancer
  selector:
    app: fodmap-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 3000