---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  labels:
    app: fodmap-react
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: fodmap-react