---
- name: Configure kubectl to EKS cluster
  shell: |
    aws eks update-kubeconfig --region {{ AWS_REGION }} --name fodmap-cluster

- name: Check Kubectl configuration
  shell: |
    kubectl get svc

- name: Check if namespace already exists
  shell: |
    kubectl get namespace fodmaNamespace
  register: namespace_info
  ignore_errors: yes
  changed_when: false

- name: Create Namespace
  shell: |
    kubectl create namespace fodmaNamespace
  when: namespace_info.rc != 0